In [337]:
!pip install -q sklearn

In [338]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import pandas as pd

!pip install -q tensorflow==2.0.0-alpha0
import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [390]:
weathers_df=pd.read_csv("weatherAUS.csv")

In [391]:
weathers_df.drop(['Date'], axis=1, inplace=True)

In [392]:
weathers_df.head()

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0   Albury     13.4     22.9       0.6          NaN       NaN           W   
1   Albury      7.4     25.1       0.0          NaN       NaN         WNW   
2   Albury     12.9     25.7       0.0          NaN       NaN         WSW   
3   Albury      9.2     28.0       0.0          NaN       NaN          NE   
4   Albury     17.5     32.3       1.0          NaN       NaN           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity3pm  Pressure9am  \
0           44.0          W        WNW  ...         22.0       1007.7   
1           44.0        NNW        WSW  ...         25.0       1010.6   
2           46.0          W        WSW  ...         30.0       1007.6   
3           24.0         SE          E  ...         16.0       1017.6   
4           41.0        ENE         NW  ...         33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [393]:
new_weathers_df = weathers_df.dropna(axis=0)

In [394]:
new_weathers_df

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
5939      Cobar     17.9     35.2       0.0         12.0      12.3   
5940      Cobar     18.4     28.9       0.0         14.8      13.0   
5942      Cobar     19.4     37.6       0.0         10.8      10.6   
5943      Cobar     21.9     38.4       0.0         11.4      12.2   
5944      Cobar     24.2     41.0       0.0         11.2       8.4   
5945      Cobar     27.1     36.1       0.0         13.0       0.0   
5946      Cobar     23.3     34.0       0.0          9.8      12.6   
5947      Cobar     16.1     34.2       0.0         14.6      13.2   
5948      Cobar     19.0     35.5       0.0         12.0      12.3   
5949      Cobar     19.7     35.5       0.0         11.0      12.7   
5950      Cobar     20.9     37.8       0.0         12.8      13.2   
5951      Cobar     23.9     39.1       0.0         13.8      12.1   
5952      Cobar     24.9     41.2       0.0         14.8      13.0   
5953      Cobar     25.2     40.5       0.0         16.4      10.3   
5954      Cobar     21.6     34.2       0.0         17.4      13.1   
5955      Cobar     18.4     31.8       0.0         16.0      12.9   
5956      Cobar     17.9     34.2       0.0         12.0      11.3   
5957      Cobar     21.4     37.5       0.0         14.8       6.9   
5958      Cobar     23.3     39.4       4.8         12.0      10.9   
5959      Cobar     25.4     33.5       0.0         13.6       3.7   
5960      Cobar     21.8     30.7       0.0          8.0       5.9   
5961      Cobar     20.3     36.0      18.0          8.2      10.5   
5962      Cobar     22.1     34.7       8.6          8.6      12.4   
5963      Cobar     19.7     37.3       0.0         14.2      13.4   
5964      Cobar     23.8     39.9       0.0         12.6      13.2   
5965      Cobar     27.0     38.7       0.0         14.2      13.0   
5966      Cobar     26.2     38.5       0.0         14.6      13.3   
5967      Cobar     25.0     39.5       0.0         14.6      13.6   
5968      Cobar     25.1     39.3       0.0         15.8      13.2   
5969      Cobar     25.2     38.5       0.0         16.2      13.1   
...         ...      ...      ...       ...          ...       ...   
139083   Darwin     24.3     31.9       0.0          6.4      10.9   
139084   Darwin     23.5     33.3       0.0          5.4      10.8   
139085   Darwin     22.4     32.2       0.0          8.0       6.3   
139086   Darwin     24.1     32.6       0.0          6.8      10.4   
139087   Darwin     22.5     32.3       0.0          6.6      10.6   
139088   Darwin     20.4     31.4       0.2          9.6       9.6   
139089   Darwin     21.9     31.6       0.0         10.0       9.9   
139090   Darwin     21.6     32.0       0.0          9.6      10.7   
139091   Darwin     22.7     31.6       0.0          7.0       7.4   
139092   Darwin     22.4     31.4       0.0          6.6       8.3   
139093   Darwin     23.3     32.4       0.0          5.4       8.9   
139094   Darwin     20.6     31.8       0.0          6.4      10.8   
139095   Darwin     20.0     30.4       0.0          9.0      10.8   
139096   Darwin     19.2     29.4       0.0          7.4      10.9   
139097   Darwin     20.6     29.4       0.0         10.6       5.4   
139098   Darwin     18.7     29.4       0.0          7.8       8.7   
139099   Darwin     19.0     29.4       0.0          7.6      10.4   
139100   Darwin     17.2     29.1       0.0          7.2      10.1   
139101   Darwin     18.3     29.8       0.0          8.4      10.5   
139102   Darwin     16.9     30.3       0.0          5.4      10.9   
139103   Darwin     19.0     30.9       0.0          5.0      10.8   
139104   Darwin     18.9     31.1       0.0          6.0      10.6   
139105   Darwin     20.2     32.1       0.0          4.8       9.9   
139106   Darwin     20.0     33.1       0.0          4.6      10.9   
139107   Darwin     21.9     33.0       0.0          5.2      10.9   
139108   Darwin  

In [395]:
pd.get_dummies(new_weathers_df['RainTomorrow'])

No  Yes
5939     1    0
5940     1    0
5942     1    0
5943     1    0
5944     1    0
5945     1    0
5946     1    0
5947     1    0
5948     1    0
5949     1    0
5950     1    0
5951     1    0
5952     1    0
5953     1    0
5954     1    0
5955     1    0
5956     1    0
5957     0    1
5958     1    0
5959     1    0
5960     0    1
5961     0    1
5962     1    0
5963     1    0
5964     1    0
5965     1    0
5966     1    0
5967     1    0
5968     1    0
5969     1    0
...     ..  ...
139083   1    0
139084   1    0
139085   1    0
139086   1    0
139087   1    0
139088   1    0
139089   1    0
139090   1    0
139091   1    0
139092   1    0
139093   1    0
139094   1    0
139095   1    0
139096   1    0
139097   1    0
139098   1    0
139099   1    0
139100   1    0
139101   1    0
139102   1    0
139103   1    0
139104   1    0
139105   1    0
139106   1    0
139107   1    0
139108   1    0
139109   1    0
139110   1    0
139111   1    0
139112   1    0

[56420 rows x 2 columns]

In [396]:
new_weathers_df["RainTomorrow"]=pd.get_dummies(new_weathers_df['RainTomorrow'], drop_first=True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [397]:
new_weathers_df

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
5939      Cobar     17.9     35.2       0.0         12.0      12.3   
5940      Cobar     18.4     28.9       0.0         14.8      13.0   
5942      Cobar     19.4     37.6       0.0         10.8      10.6   
5943      Cobar     21.9     38.4       0.0         11.4      12.2   
5944      Cobar     24.2     41.0       0.0         11.2       8.4   
5945      Cobar     27.1     36.1       0.0         13.0       0.0   
5946      Cobar     23.3     34.0       0.0          9.8      12.6   
5947      Cobar     16.1     34.2       0.0         14.6      13.2   
5948      Cobar     19.0     35.5       0.0         12.0      12.3   
5949      Cobar     19.7     35.5       0.0         11.0      12.7   
5950      Cobar     20.9     37.8       0.0         12.8      13.2   
5951      Cobar     23.9     39.1       0.0         13.8      12.1   
5952      Cobar     24.9     41.2       0.0         14.8      13.0   
5953      Cobar     25.2     40.5       0.0         16.4      10.3   
5954      Cobar     21.6     34.2       0.0         17.4      13.1   
5955      Cobar     18.4     31.8       0.0         16.0      12.9   
5956      Cobar     17.9     34.2       0.0         12.0      11.3   
5957      Cobar     21.4     37.5       0.0         14.8       6.9   
5958      Cobar     23.3     39.4       4.8         12.0      10.9   
5959      Cobar     25.4     33.5       0.0         13.6       3.7   
5960      Cobar     21.8     30.7       0.0          8.0       5.9   
5961      Cobar     20.3     36.0      18.0          8.2      10.5   
5962      Cobar     22.1     34.7       8.6          8.6      12.4   
5963      Cobar     19.7     37.3       0.0         14.2      13.4   
5964      Cobar     23.8     39.9       0.0         12.6      13.2   
5965      Cobar     27.0     38.7       0.0         14.2      13.0   
5966      Cobar     26.2     38.5       0.0         14.6      13.3   
5967      Cobar     25.0     39.5       0.0         14.6      13.6   
5968      Cobar     25.1     39.3       0.0         15.8      13.2   
5969      Cobar     25.2     38.5       0.0         16.2      13.1   
...         ...      ...      ...       ...          ...       ...   
139083   Darwin     24.3     31.9       0.0          6.4      10.9   
139084   Darwin     23.5     33.3       0.0          5.4      10.8   
139085   Darwin     22.4     32.2       0.0          8.0       6.3   
139086   Darwin     24.1     32.6       0.0          6.8      10.4   
139087   Darwin     22.5     32.3       0.0          6.6      10.6   
139088   Darwin     20.4     31.4       0.2          9.6       9.6   
139089   Darwin     21.9     31.6       0.0         10.0       9.9   
139090   Darwin     21.6     32.0       0.0          9.6      10.7   
139091   Darwin     22.7     31.6       0.0          7.0       7.4   
139092   Darwin     22.4     31.4       0.0          6.6       8.3   
139093   Darwin     23.3     32.4       0.0          5.4       8.9   
139094   Darwin     20.6     31.8       0.0          6.4      10.8   
139095   Darwin     20.0     30.4       0.0          9.0      10.8   
139096   Darwin     19.2     29.4       0.0          7.4      10.9   
139097   Darwin     20.6     29.4       0.0         10.6       5.4   
139098   Darwin     18.7     29.4       0.0          7.8       8.7   
139099   Darwin     19.0     29.4       0.0          7.6      10.4   
139100   Darwin     17.2     29.1       0.0          7.2      10.1   
139101   Darwin     18.3     29.8       0.0          8.4      10.5   
139102   Darwin     16.9     30.3       0.0          5.4      10.9   
139103   Darwin     19.0     30.9       0.0          5.0      10.8   
139104   Darwin     18.9     31.1       0.0          6.0      10.6   
139105   Darwin     20.2     32.1       0.0          4.8       9.9   
139106   Darwin     20.0     33.1       0.0          4.6      10.9   
139107   Darwin     21.9     33.0       0.0          5.2      10.9   
139108   Darwin  

In [398]:
train, test = train_test_split(new_weathers_df, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), '훈련 샘플')
print(len(val), '검증 샘플')
print(len(test), '테스트 샘플')

36108 훈련 샘플
9028 검증 샘플
11284 테스트 샘플


In [399]:
# 판다스 데이터프레임으로부터 tf.data 데이터셋을 만들기 위한 함수
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('RainTomorrow')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [400]:
batch_size = 32 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [401]:
# 특성 열을 만들고 배치 데이터를 변환하는 함수
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

In [402]:
# 특성 열을 시험해 보기 위해 샘플 배치를 만듭니다.
example_batch = next(iter(train_ds))[0]

In [403]:
# 특성 열을 만들고 배치 데이터를 변환하는 함수
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

In [404]:
MinTemp = feature_column.numeric_column("MinTemp")
demo(MinTemp)

[[16.2]
 [12.6]
 [20.3]
 [11. ]
 [23.5]
 [29.2]
 [ 7.8]
 [ 6.7]
 [ 4.4]
 [16.8]
 [11.8]
 [26.5]
 [30.5]
 [ 7.7]
 [15.5]
 [ 6.4]
 [ 4.3]
 [14.5]
 [ 7.9]
 [ 5.3]
 [ 3.1]
 [ 7.3]
 [ 7.5]
 [ 7.9]
 [18. ]
 [13.3]
 [16.2]
 [ 3.5]
 [16.2]
 [11.7]
 [23.1]
 [13.2]]


In [405]:
MaxTemp = feature_column.numeric_column("MaxTemp")
demo(MaxTemp)

[[30.7]
 [27.7]
 [34.4]
 [29.3]
 [27.6]
 [34.3]
 [16.5]
 [15.7]
 [12.9]
 [23.3]
 [20.5]
 [33.1]
 [44.2]
 [12.5]
 [20.8]
 [30.4]
 [14.8]
 [27.2]
 [28.2]
 [24.7]
 [20.9]
 [25.1]
 [19.3]
 [18.4]
 [42. ]
 [19.9]
 [27.8]
 [ 8.3]
 [20.1]
 [19.4]
 [40.8]
 [28.6]]


In [406]:
Rainfall = feature_column.numeric_column("Rainfall")
demo(Rainfall)

[[ 0. ]
 [ 0. ]
 [17.2]
 [ 0. ]
 [ 0.4]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [22.2]
 [ 0.6]
 [ 5.6]
 [ 0. ]
 [ 0. ]
 [ 1.2]
 [ 2.4]
 [ 0. ]
 [ 0.4]
 [ 6.4]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [ 2.2]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [25.6]
 [ 0.4]
 [ 0.6]
 [ 0. ]
 [ 0. ]]


In [407]:
Evaporation = feature_column.numeric_column("Evaporation")
demo(Evaporation)

[[ 6. ]
 [ 4. ]
 [ 7.8]
 [ 7. ]
 [ 1.2]
 [ 8. ]
 [ 7.2]
 [ 0.6]
 [ 4.2]
 [ 8. ]
 [ 9.6]
 [ 5.4]
 [20.4]
 [ 1.6]
 [ 4.8]
 [ 4.6]
 [ 1.6]
 [ 1.8]
 [ 5.6]
 [ 5.6]
 [ 2.4]
 [ 2.4]
 [ 2.4]
 [ 2.4]
 [12. ]
 [ 9.8]
 [ 9.6]
 [ 4.2]
 [ 1.2]
 [ 4.6]
 [ 7.2]
 [10. ]]


In [408]:
Sunshine = feature_column.numeric_column("Sunshine")
demo(Sunshine)

[[11.1]
 [11.1]
 [12.8]
 [ 8.4]
 [ 2.6]
 [ 7.5]
 [ 9.8]
 [ 2.2]
 [ 7.4]
 [ 2.3]
 [11. ]
 [ 8.2]
 [10.3]
 [ 6.3]
 [ 8.5]
 [12. ]
 [ 7. ]
 [12.5]
 [10.7]
 [12. ]
 [10. ]
 [10.3]
 [ 7.8]
 [ 9.2]
 [13.3]
 [ 4.3]
 [11. ]
 [ 0.4]
 [ 6.4]
 [ 8.8]
 [11.5]
 [10.6]]


In [409]:
WindGustSpeed = feature_column.numeric_column("WindGustSpeed")
demo(WindGustSpeed)

[[37.]
 [30.]
 [24.]
 [39.]
 [46.]
 [37.]
 [54.]
 [20.]
 [61.]
 [63.]
 [54.]
 [50.]
 [59.]
 [35.]
 [69.]
 [26.]
 [26.]
 [39.]
 [30.]
 [37.]
 [31.]
 [56.]
 [43.]
 [31.]
 [35.]
 [48.]
 [39.]
 [67.]
 [20.]
 [43.]
 [37.]
 [72.]]


In [410]:
WindSpeed9am = feature_column.numeric_column("WindSpeed9am")
demo(WindSpeed9am)

[[24.]
 [17.]
 [ 4.]
 [ 2.]
 [22.]
 [15.]
 [22.]
 [11.]
 [35.]
 [35.]
 [24.]
 [13.]
 [39.]
 [19.]
 [31.]
 [20.]
 [11.]
 [ 7.]
 [15.]
 [ 6.]
 [19.]
 [20.]
 [17.]
 [ 9.]
 [17.]
 [30.]
 [ 7.]
 [31.]
 [11.]
 [24.]
 [17.]
 [19.]]


In [411]:
WindSpeed3pm = feature_column.numeric_column("WindSpeed3pm")
demo(WindSpeed3pm)

[[24.]
 [15.]
 [ 7.]
 [17.]
 [28.]
 [28.]
 [33.]
 [ 7.]
 [28.]
 [35.]
 [31.]
 [28.]
 [26.]
 [24.]
 [33.]
 [13.]
 [15.]
 [20.]
 [ 7.]
 [17.]
 [11.]
 [13.]
 [24.]
 [11.]
 [20.]
 [24.]
 [19.]
 [24.]
 [15.]
 [22.]
 [ 9.]
 [35.]]


In [412]:
Humidity9am = feature_column.numeric_column("Humidity9am")
demo(Humidity9am)

[[34.]
 [56.]
 [71.]
 [34.]
 [90.]
 [74.]
 [68.]
 [76.]
 [75.]
 [66.]
 [77.]
 [72.]
 [15.]
 [47.]
 [66.]
 [65.]
 [94.]
 [73.]
 [46.]
 [71.]
 [65.]
 [74.]
 [68.]
 [73.]
 [25.]
 [63.]
 [46.]
 [91.]
 [82.]
 [61.]
 [27.]
 [51.]]


In [413]:
Humidity3pm = feature_column.numeric_column("Humidity3pm")
demo(Humidity3pm)

[[45.]
 [30.]
 [26.]
 [22.]
 [85.]
 [64.]
 [30.]
 [65.]
 [53.]
 [53.]
 [37.]
 [63.]
 [10.]
 [44.]
 [57.]
 [23.]
 [63.]
 [46.]
 [12.]
 [25.]
 [37.]
 [34.]
 [47.]
 [50.]
 [ 9.]
 [56.]
 [54.]
 [81.]
 [76.]
 [46.]
 [16.]
 [30.]]


In [414]:
Pressure9am = feature_column.numeric_column("Pressure9am")
demo(Pressure9am)

[[1016.3]
 [1020. ]
 [1007.6]
 [1016.3]
 [1017.6]
 [1013.5]
 [1017.3]
 [1024.2]
 [1004.7]
 [1013.8]
 [1012.4]
 [1006.5]
 [1011.2]
 [1032.9]
 [1012.7]
 [1024. ]
 [1026.2]
 [1011.7]
 [1022.9]
 [1022.1]
 [1023.7]
 [1020.2]
 [1012.2]
 [1032.2]
 [1015.3]
 [1028.1]
 [1009. ]
 [1022.2]
 [1018.2]
 [1009.9]
 [1010.3]
 [1007. ]]


In [415]:
Pressure3pm = feature_column.numeric_column("Pressure3pm")
demo(Pressure3pm)

[[1012.6]
 [1016.5]
 [1003.6]
 [1013.9]
 [1015.9]
 [1009. ]
 [1016.5]
 [1022.3]
 [1008.7]
 [1012.2]
 [1012.4]
 [1003.4]
 [1009.6]
 [1031.1]
 [1011.6]
 [1020.5]
 [1024.5]
 [1009.9]
 [1019.3]
 [1018.8]
 [1021.5]
 [1016. ]
 [1003.6]
 [1028.9]
 [1012.9]
 [1026.7]
 [1009.8]
 [1023.1]
 [1016.6]
 [1010.2]
 [1005.2]
 [1004.6]]


In [416]:
Cloud9am = feature_column.numeric_column("Cloud9am")
demo(Cloud9am)

[[0.]
 [1.]
 [1.]
 [3.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [2.]
 [8.]
 [1.]
 [7.]
 [3.]
 [4.]
 [1.]
 [1.]
 [4.]
 [1.]
 [0.]
 [5.]
 [1.]
 [1.]
 [1.]
 [7.]
 [1.]
 [7.]
 [5.]
 [8.]
 [4.]
 [4.]]


In [417]:
Cloud3pm = feature_column.numeric_column("Cloud3pm")
demo(Cloud3pm)

[[0.]
 [2.]
 [1.]
 [6.]
 [8.]
 [1.]
 [1.]
 [7.]
 [5.]
 [7.]
 [5.]
 [7.]
 [4.]
 [7.]
 [4.]
 [5.]
 [6.]
 [5.]
 [5.]
 [2.]
 [2.]
 [5.]
 [7.]
 [1.]
 [1.]
 [5.]
 [1.]
 [8.]
 [6.]
 [5.]
 [2.]
 [2.]]


In [418]:
Temp9am = feature_column.numeric_column("Temp9am")
demo(Temp9am)

[[21.8]
 [21.6]
 [26.8]
 [22.3]
 [25.3]
 [30.5]
 [11.2]
 [10.1]
 [ 5.4]
 [18.5]
 [13.9]
 [28.9]
 [35.4]
 [ 9.1]
 [18.1]
 [14.2]
 [ 7. ]
 [20.2]
 [18.6]
 [14.1]
 [12.5]
 [15.7]
 [13.6]
 [11.6]
 [30.9]
 [15.9]
 [24. ]
 [ 8. ]
 [18. ]
 [14.2]
 [33.1]
 [20.6]]


In [419]:
Temp3pm = feature_column.numeric_column("Temp3pm")
demo(Temp3pm)

[[28.6]
 [26.9]
 [34.2]
 [26.9]
 [25.3]
 [33.6]
 [15.5]
 [15.1]
 [10.8]
 [22.4]
 [19.4]
 [32.3]
 [42.4]
 [10.7]
 [20.2]
 [29.3]
 [14.3]
 [25.8]
 [27.2]
 [23.8]
 [20. ]
 [24.5]
 [17.9]
 [17.8]
 [41.5]
 [17.9]
 [23.5]
 [ 7.8]
 [19.5]
 [17.7]
 [39.4]
 [26.9]]


In [420]:
new_weathers_df['Location'].unique()

array(['Cobar', 'CoffsHarbour', 'Moree', 'NorfolkIsland', 'Sydney',
       'SydneyAirport', 'WaggaWagga', 'Williamtown', 'Canberra', 'Sale',
       'MelbourneAirport', 'Melbourne', 'Mildura', 'Portland', 'Watsonia',
       'Brisbane', 'Cairns', 'Townsville', 'MountGambier', 'Nuriootpa',
       'Woomera', 'PerthAirport', 'Perth', 'Hobart', 'AliceSprings',
       'Darwin'], dtype=object)

In [421]:

Location = feature_column.categorical_column_with_vocabulary_list(
      'Location', ['Cobar', 'CoffsHarbour', 'Moree', 'NorfolkIsland', 'Sydney',
       'SydneyAirport', 'WaggaWagga', 'Williamtown', 'Canberra', 'Sale',
       'MelbourneAirport', 'Melbourne', 'Mildura', 'Portland', 'Watsonia',
       'Brisbane', 'Cairns', 'Townsville', 'MountGambier', 'Nuriootpa',
       'Woomera', 'PerthAirport', 'Perth', 'Hobart', 'AliceSprings',
       'Darwin'])

Location_one_hot = feature_column.indicator_column(Location)
demo(Location_one_hot)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1.]
 [0.

In [422]:
new_weathers_df['WindGustDir'].unique()

array(['SSW', 'S', 'NNE', 'WNW', 'N', 'SE', 'ENE', 'NE', 'E', 'SW', 'W',
       'WSW', 'NNW', 'ESE', 'SSE', 'NW'], dtype=object)

In [423]:
WindGustDir = feature_column.categorical_column_with_vocabulary_list(
      'WindGustDir', ['SSW', 'S', 'NNE', 'WNW', 'N', 'SE', 'ENE', 'NE', 'E', 'SW', 'W',
       'WSW', 'NNW', 'ESE', 'SSE', 'NW'])

WindGustDir_one_hot = feature_column.indicator_column(WindGustDir)
demo(WindGustDir_one_hot)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [424]:
new_weathers_df['WindDir9am'].unique()

array(['ENE', 'SSE', 'NNE', 'WNW', 'NW', 'N', 'S', 'SE', 'NE', 'W', 'SSW',
       'E', 'NNW', 'ESE', 'WSW', 'SW'], dtype=object)

In [425]:
WindDir9am = feature_column.categorical_column_with_vocabulary_list(
      'WindDir9am', ['ENE', 'SSE', 'NNE', 'WNW', 'NW', 'N', 'S', 'SE', 'NE', 'W', 'SSW',
       'E', 'NNW', 'ESE', 'WSW', 'SW'])

WindDir9am_one_hot = feature_column.indicator_column(WindDir9am)
demo(WindDir9am_one_hot)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [426]:
new_weathers_df['WindDir3pm'].unique()

array(['SW', 'SSE', 'NNW', 'WSW', 'WNW', 'S', 'ENE', 'N', 'SE', 'NNE',
       'NW', 'E', 'ESE', 'NE', 'SSW', 'W'], dtype=object)

In [427]:
WindDir3pm = feature_column.categorical_column_with_vocabulary_list(
      'WindDir3pm', ['SW', 'SSE', 'NNW', 'WSW', 'WNW', 'S', 'ENE', 'N', 'SE', 'NNE',
       'NW', 'E', 'ESE', 'NE', 'SSW', 'W'])

WindDir3pm_one_hot = feature_column.indicator_column(WindDir3pm)
demo(WindDir3pm_one_hot)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [428]:
RainToday = feature_column.categorical_column_with_vocabulary_list(
      'RainToday', ['Yes', 'No'])

RainToday_one_hot = feature_column.indicator_column(RainToday)
demo(RainToday_one_hot)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [429]:
new_weathers_df.columns

Index(['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [430]:
feature_columns = []
# numeric cols
for header in ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', 
               'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 
               'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm']:
  feature_columns.append(feature_column.numeric_column(header))

In [431]:

Location = feature_column.categorical_column_with_vocabulary_list(
      'Location', ['Cobar', 'CoffsHarbour', 'Moree', 'NorfolkIsland', 'Sydney',
       'SydneyAirport', 'WaggaWagga', 'Williamtown', 'Canberra', 'Sale',
       'MelbourneAirport', 'Melbourne', 'Mildura', 'Portland', 'Watsonia',
       'Brisbane', 'Cairns', 'Townsville', 'MountGambier', 'Nuriootpa',
       'Woomera', 'PerthAirport', 'Perth', 'Hobart', 'AliceSprings',
       'Darwin'])

Location_one_hot = feature_column.indicator_column(Location)
feature_columns.append(Location_one_hot)


In [432]:
WindGustDir = feature_column.categorical_column_with_vocabulary_list(
      'WindGustDir', ['SSW', 'S', 'NNE', 'WNW', 'N', 'SE', 'ENE', 'NE', 'E', 'SW', 'W',
       'WSW', 'NNW', 'ESE', 'SSE', 'NW'])
WindGustDir_one_hot = feature_column.indicator_column(WindGustDir)
feature_columns.append(WindGustDir_one_hot)

In [433]:
WindDir9am = feature_column.categorical_column_with_vocabulary_list(
      'WindDir9am', ['ENE', 'SSE', 'NNE', 'WNW', 'NW', 'N', 'S', 'SE', 'NE', 'W', 'SSW',
       'E', 'NNW', 'ESE', 'WSW', 'SW'])

WindDir9am_one_hot = feature_column.indicator_column(WindDir9am)
feature_columns.append(WindDir9am_one_hot)

In [434]:
WindDir3pm = feature_column.categorical_column_with_vocabulary_list(
      'WindDir3pm', ['SW', 'SSE', 'NNW', 'WSW', 'WNW', 'S', 'ENE', 'N', 'SE', 'NNE',
       'NW', 'E', 'ESE', 'NE', 'SSW', 'W'])

WindDir3pm_one_hot = feature_column.indicator_column(WindDir3pm)
feature_columns.append(WindDir3pm_one_hot)

In [435]:
RainToday = feature_column.categorical_column_with_vocabulary_list(
      'RainToday', ['Yes', 'No'])

RainToday_one_hot = feature_column.indicator_column(RainToday)
feature_columns.append(RainToday_one_hot)

In [436]:
feature_columns

[NumericColumn(key='MinTemp', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='MaxTemp', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Rainfall', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Evaporation', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Sunshine', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='WindGustSpeed', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='WindSpeed9am', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='WindSpeed3pm', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Humidity9am', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='Humidity3pm', shape=(1,), default_value=None,

In [437]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

In [438]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [441]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'],
              run_eagerly=True)

model.fit(train_ds,
          validation_data=val_ds,
          epochs=5)

Epoch 1/5
1129/1129 [==============================] - 27s 24ms/step - loss: 3.3973 - accuracy: 0.7824 - val_loss: 3.4560 - val_accuracy: 0.7760
Epoch 2/5
1129/1129 [==============================] - 27s 24ms/step - loss: 3.3973 - accuracy: 0.7824 - val_loss: 3.4560 - val_accuracy: 0.7760
Epoch 3/5
1129/1129 [==============================] - 28s 25ms/step - loss: 3.3973 - accuracy: 0.7824 - val_loss: 3.4560 - val_accuracy: 0.7760
Epoch 4/5
1129/1129 [==============================] - 29s 26ms/step - loss: 3.3973 - accuracy: 0.7824 - val_loss: 3.4560 - val_accuracy: 0.7760
Epoch 5/5
1129/1129 [==============================] - 27s 24ms/step - loss: 3.3973 - accuracy: 0.7824 - val_loss: 3.4560 - val_accuracy: 0.7760


In [442]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

353/353 [==============================] - 5s 14ms/step - loss: 3.3521 - accuracy: 0.7826
Accuracy 0.78261256


In [443]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_features_152 (DenseFea multiple                  0         
_________________________________________________________________
dense_33 (Dense)             multiple                  23808     
_________________________________________________________________
dense_34 (Dense)             multiple                  65792     
_________________________________________________________________
dense_35 (Dense)             multiple                  257       
Total params: 89,857
Trainable params: 89,857
Non-trainable params: 0
_________________________________________________________________


In [445]:
tf.math.confusion_matrix(
    test_ds,
    'RainTomorrow',
)

ValueError: Attempt to convert a value (<BatchDataset shapes: ({Location: (None,), MinTemp: (None,), MaxTemp: (None,), Rainfall: (None,), Evaporation: (None,), Sunshine: (None,), WindGustDir: (None,), WindGustSpeed: (None,), WindDir9am: (None,), WindDir3pm: (None,), WindSpeed9am: (None,), WindSpeed3pm: (None,), Humidity9am: (None,), Humidity3pm: (None,), Pressure9am: (None,), Pressure3pm: (None,), Cloud9am: (None,), Cloud3pm: (None,), Temp9am: (None,), Temp3pm: (None,), RainToday: (None,), RISK_MM: (None,)}, (None,)), types: ({Location: tf.string, MinTemp: tf.float32, MaxTemp: tf.float32, Rainfall: tf.float32, Evaporation: tf.float32, Sunshine: tf.float32, WindGustDir: tf.string, WindGustSpeed: tf.float32, WindDir9am: tf.string, WindDir3pm: tf.string, WindSpeed9am: tf.float32, WindSpeed3pm: tf.float32, Humidity9am: tf.float32, Humidity3pm: tf.float32, Pressure9am: tf.float32, Pressure3pm: tf.float32, Cloud9am: tf.float32, Cloud3pm: tf.float32, Temp9am: tf.float32, Temp3pm: tf.float32, RainToday: tf.string, RISK_MM: tf.float32}, tf.int32)>) with an unsupported type (<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>) to a Tensor.

In [ ]:
test_ds.

In [448]:
model.predict_classes(test_ds, verbose=1)

ValueError: The `batch_size` argument must not be specified when using dataset as an input.

In [452]:
test_ds.batch(batch_size=0)

InvalidArgumentError: Batch size must be greater than zero. [Op:BatchDatasetV2]